
					
				


				<li class="dropahint"><a href="#"><img src="<?php echo $this->getSkinUrl('images/drophint.png') ?>"/>DROP A HINT</span></a></li>
				
				
				
				<li class="pinit" id="pinterestshare"> 				 
				<a style="background-image:none;" href="#" onClick="MyWindow=window.open('<?php echo 'http://www.pinterest.com/pin/create/button/' . $_uv; ?>','MyWindow',width=600,height=300); return false;" title="<?php echo $this->__('Pint it') ?>" ><img src="<?php echo $this->getSkinUrl('images/pinit.png') ?>"/>PIN IT</a>
				</li>
			
			
				
				
				<li  id="facebookshare">				
					<a href="#" onClick="MyWindow=window.open('<?php echo 'http://www.facebook.com/sharer/sharer.php' . $_u; ?>','MyWindow',width=600,height=300); return false;" title="<?php echo $this->__('Share it') ?>">
						<img src="<?php echo $this->getSkinUrl('images/fbshare.png') ?>"/>SHARE IT</a>
				</li>


				<li class="livechat"><a href="#"><img src="<?php echo $this->getSkinUrl('images/livechat.png') ?>"/>LIVE CHAT</span></a></li>


				<li class="callus"><a href="#"><img src="<?php echo $this->getSkinUrl('images/callus.png') ?>"/>CALL US</a></li>

